# This is a basic workflow to help you get started with Actions

name: Manualy Run with Parameter

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}
    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
      
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v5.2

    - name: Current branch name
      run: |
        echo "::set-env name=BRANCH_NAME::${{ steps.branch-name.outputs.current_branch }}"
        
    # print branch name
    - name: Get branch name
      run: echo 'The branch name is' $BRANCH_NAME        

